"""
Smart Contract Deployment Script
Deploys OrderEscrow contract to Ganache and saves configuration
"""

import json
import os
import sys
from pathlib import Path
from web3 import Web3

def deploy_contract():
    """Deploy OrderEscrow contract to Ganache"""
    
    print("🚀 Deploying OrderEscrow Contract to Ganache")
    print("=" * 60)
    
    # Paths
    project_root = Path(__file__).parent.parent
    contract_json = project_root / "backend" / "contracts" / "OrderEscrow.json"
    env_file = project_root / ".env"
    
    # Check if contract is compiled
    if not contract_json.exists():
        print(f"❌ Error: Contract not compiled!")
        print(f"   Run: python scripts/compile_contract.py")
        sys.exit(1)
    
    # Load contract
    print(f"📄 Loading contract from: {contract_json}")
    with open(contract_json, 'r') as f:
        contract_data = json.load(f)
    
    abi = contract_data['abi']
    bytecode = contract_data['bytecode']
    
    # Connect to Ganache
    ganache_url = "http://127.0.0.1:8545"
    print(f"🔌 Connecting to Ganache at {ganache_url}...")
    
    try:
        w3 = Web3(Web3.HTTPProvider(ganache_url))
        
        if not w3.is_connected():
            print("❌ Error: Cannot connect to Ganache!")
            print()
            print("Please start Ganache first:")
            print("   ganache --port 8545 --deterministic")
            sys.exit(1)
        
        print("✅ Connected to Ganache")
        print(f"   Network ID: {w3.eth.chain_id}")
        print(f"   Latest Block: {w3.eth.block_number}")
        print()
        
    except Exception as e:
        print(f"❌ Connection failed: {e}")
        sys.exit(1)
    
    # Get admin account (first Ganache account)
    accounts = w3.eth.accounts
    admin_account = accounts[0]
    
    print(f"👤 Admin Account: {admin_account}")
    balance = w3.eth.get_balance(admin_account)
    print(f"   Balance: {w3.from_wei(balance, 'ether')} ETH")
    print()
    
    # Deploy contract
    print("📤 Deploying contract...")
    try:
        Contract = w3.eth.contract(abi=abi, bytecode=bytecode)
        
        # Build transaction
        tx_hash = Contract.constructor().transact({
            'from': admin_account,
            'gas': 3000000
        })
        
        print(f"   Transaction Hash: {tx_hash.hex()}")
        print("   Waiting for confirmation...")
        
        # Wait for receipt
        tx_receipt = w3.eth.wait_for_transaction_receipt(tx_hash)
        contract_address = tx_receipt.contractAddress
        
        print()
        print("✅ Contract deployed successfully!")
        print(f"📍 Contract Address: {contract_address}")
        print(f"⛽ Gas Used: {tx_receipt.gasUsed}")
        print()
        
    except Exception as e:
        print(f"❌ Deployment failed: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)
    
    # Get admin private key from Ganache
    # Note: In Ganache with --deterministic, the first account's private key is always the same
    # For security, this should be stored securely in production
    print("🔑 Ganache Account Details:")
    print("   ⚠️  IMPORTANT: These are test keys from Ganache")
    print("   ⚠️  NEVER use these in production!")
    print()
    print("   When you started Ganache, it displayed private keys.")
    print("   Copy the private key for account (0) and add it to .env")
    print()
    
    # Create/update .env file
    env_content = f"""# Blockchain Configuration (Generated by deploy_contract.py)
WEB3_PROVIDER_URI=http://127.0.0.1:8545
SMART_CONTRACT_ADDRESS={contract_address}
SMART_CONTRACT_ABI_PATH=backend/contracts/OrderEscrow.json

# System Wallet (Admin Account from Ganache)
SYSTEM_WALLET_ADDRESS={admin_account}
# IMPORTANT: Add your Ganache private key here
# SYSTEM_WALLET_PRIVATE_KEY=0x... (get from Ganache startup logs)

# Other Configuration
# Add your other environment variables below
"""
    
    # Check if .env exists
    if env_file.exists():
        print("📝 Updating existing .env file...")
        # Read existing content
        with open(env_file, 'r') as f:
            existing_content = f.read()
        
        # Update blockchain section
        lines = existing_content.split('\n')
        new_lines = []
        skip_until_blank = False
        
        for line in lines:
            if '# Blockchain Configuration' in line:
                skip_until_blank = True
                continue
            if skip_until_blank:
                if line.strip() == '' or line.startswith('#'):
                    skip_until_blank = False
                else:
                    continue
            new_lines.append(line)
        
        # Add new blockchain config at the top
        final_content = env_content + '\n' + '\n'.join(new_lines)
        
    else:
        print("📝 Creating new .env file...")
        final_content = env_content
    
    with open(env_file, 'w') as f:
        f.write(final_content)
    
    print(f"💾 Configuration saved to: {env_file}")
    print()
    
    # Summary
    print("=" * 60)
    print("✅ DEPLOYMENT COMPLETE!")
    print("=" * 60)
    print()
    print("📋 Next Steps:")
    print()
    print("1. Add your Ganache private key to .env file:")
    print(f"   SYSTEM_WALLET_PRIVATE_KEY=0x...")
    print()
    print("2. Test the connection:")
    print("   python scripts/test_blockchain_connection.py")
    print()
    print("3. Start your Flask backend:")
    print("   cd backend && python app.py")
    print()
    print("🎉 Happy blockchain development!")
    print()

if __name__ == "__main__":
    deploy_contract()
